language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts à exécuter en guise de tests
before_script:
  - echo "no tests"

script:
  - docker-compose -f docker-compose-build.yaml build
  - docker tag udagram-api-feed oury011/udagram-api-feed:v1
  - docker tag udagram-api-user oury011/udagram-api-user:v1
  - docker tag udagram-reverseproxy oury011/udagram-reverseproxy:v1
  - docker tag udagram-frontend:local oury011/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push oury011/udagram-api-feed:v1
  - docker push oury011/udagram-api-user:v1
  - docker push oury011/udagram-reverseproxy:v1
  - docker push oury011/udagram-frontend:v1