apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: oury011/udagram-api-feed:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
          envFrom:
            - configMapRef:
                name: env-config-map
            - secretRef:
                name: env-pg-secret
          
          
