# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and push images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo "Welcome to my first Github pipeline"
    - run: docker-compose -f docker-compose-build.yaml build
    - run: docker tag reverseproxy amadou011/reverseproxy:v1
    - run: docker tag udagram-api-feed amadou011/udagram-api-feed:v1
    - run: docker tag udagram-api-user amadou011/udagram-api-user:v1
    - run: docker tag udagram-frontend:local amadou011/udagram-frontend:v1
    - run: echo "${{ secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}"
    - run: docker push amadou011/reverseproxy:v1
    - run: docker push amadou011/udagram-api-feed:v1
    - run: docker push amadou011/udagram-api-user:v1
    - run: docker push amadou011/udagram-frontend:v1


